apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: keptn
    meta.helm.sh/release-namespace: keptn
  creationTimestamp: "2022-11-06T16:28:51Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: keptn
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keptn-ortelius-service
    app.kubernetes.io/version: 0.0.1
    helm.sh/chart: keptn-ortelius-service-0.0.1
  name: keptn-keptn-ortelius-service
  namespace: keptn
  resourceVersion: "24809"
  uid: 56b4b31b-214d-4db0-b25c-0b95fd9443f5
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: keptn
      app.kubernetes.io/name: keptn-ortelius-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: keptn
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: keptn-ortelius-service
        app.kubernetes.io/version: 0.0.1
        helm.sh/chart: keptn-ortelius-service-0.0.1
    spec:
      containers:
      - env:
        - name: env
          value: production
        - name: LOG_LEVEL
          value: debug
        - name: PUBSUB_TOPIC
          value: sh.keptn.>
        - name: K8S_DEPLOYMENT_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app.kubernetes.io/name']
        - name: K8S_DEPLOYMENT_VERSION
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app.kubernetes.io/version']
        - name: K8S_DEPLOYMENT_COMPONENT
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app.kubernetes.io/component']
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: bradmccoydev/keptn-ortelius-service:0.0.1
        imagePullPolicy: IfNotPresent
        name: keptn-ortelius-service
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: keptn-keptn-ortelius-service
      serviceAccountName: keptn-keptn-ortelius-service
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2022-11-06T16:28:51Z"
    lastUpdateTime: "2022-11-06T16:28:51Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2022-11-06T16:38:52Z"
    lastUpdateTime: "2022-11-06T16:38:52Z"
    message: ReplicaSet "keptn-keptn-ortelius-service-f4b56d77b" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
