apiVersion: v2
appVersion: 10.0.0
dependencies:
- name: ms-dep-pkg-cud
  repository: https://ortelius.github.io/ms-dep-pkg-cud/
  version: 10.0.1
- name: ms-dep-pkg-r
  repository: https://ortelius.github.io/ms-dep-pkg-r/
  version: 10.0.1
- name: ms-textfile-crud
  repository: https://ortelius.github.io/ms-textfile-crud/
  version: 10.0.1
- name: ms-compitem-crud
  repository: https://ortelius.github.io/ms-compitem-crud/
  version: 10.0.1
- name: ms-validate-user
  repository: https://ortelius.github.io/ms-validate-user/
  version: 10.0.1
- name: ms-scorecard
  repository: https://ortelius.github.io/ms-scorecard/
  version: 10.0.38
description: Ortelius
home: https://www.ortelius.io
icon: https://ortelius.github.io/ortelius-charts/logo.png
keywords:
- Service Catalog
- Microservices
- SBOM
name: ortelius
type: application
version: 10.0.7
