---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ms-nginx-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ms-nginx
            port:
              number: 80
