DockerRepo: quay.io/ortelius/ms-compitem-crud
DockerSha: f1639b6517cf
DockerTag: deploy-v10.0.0.104-g58a578d
image:
  repository: quay.io/ortelius/ms-compitem-crud
  tag: main-v10.0.3-g449e79
  sha: sha256:2d00c0e3b6fccd754b0a757199939eb8c2cd676f5d1e71031b96ba6fa8faddfa
---
DockerRepo: quay.io/ortelius/ms-dep-pkg-cud
DockerSha: d464014a0b25
DockerTag: deploy-v10.0.0.86-g960945e
image:
  repository: quay.io/ortelius/ms-dep-pkg-cud
  tag: main-v10.0.2-geffaa5
  sha: sha256:b5a13b55c5497493bcca919e0dc039e2585e2f73fc827fef2c85e34ee0e647a8
---
DockerRepo: quay.io/ortelius/ms-dep-pkg-r
DockerSha: 3bfe40bf649b
DockerTag: deploy-v10.0.0.97-gfac8f41
image:
  repository: quay.io/ortelius/ms-dep-pkg-r
  tag: main-v10.0.4-g564d43
  sha: sha256:1ca46922d3e5f4617d6d826d85e009e4d575297844bd9717582f747017259cec
---
affinity: {}
fullnameOverride: ''
image:
  pullPolicy: Always
  repository: quay.io/ortelius/ms-general
  tag: svc_cat-v10.0.6-g78c39e
  sha: sha256:ee60e6500125dd669a6a5db1dbe71f0d7553e45712304b40bab715b79652ce70
ingress:
  annotations: {}
  enabled: false
  hosts:
    - chart-example.local
  paths: []
  tls: []
nameOverride: ''
nodeSelector: {}
replicaCount: 1
resources: {}
service:
  port: 80
  type: ClusterIP
tolerations: []
jwt:
  privateKey: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQ3QyOFRjd1FBUGdNZGIKaGg4RVlqejJzaVJSbXhkcmZiNk5JejlvVGZNN0gzbDZkcGpqdEpUbGY1d3UrN1ltWFdTZExOTEV4V25IZjVPVQp5Mjl1NDlUV0NBWDZod1VoRmJyLzl4eWNyNWFNd3NKb2I4Qmd1WGRrbG1lTWYyMU5qR1dxd211TjdkL3M5L3BFCk9rSnppMUN1YlhaZzRxY0lZVmQxMS9UcDNHYnZmUTRIQ0FmUThXU1Q0eWdpUHhGMWxDc08wa3ZpVFN6V1VrKzgKVEFyeU5vUzdieEdpYjhkVWQ1b3F0Rk9zdGFPekZ1Y0F2Y24xL25SemJoT09wNWM1RVAvUGVQeVZ4MStHUWxWZgptcVA2cWN2d3NNOGw2Q1RxMVd2aTN0em1DQ3Q1SXFKVXNhL1JjNHg1d2RWN1FPWTRtbmFld05VZXhKODkzRUI2CjZwSnBxMDlKQWdNQkFBRUNnZ0VBRzZaSlFnSnFZV0lpL1JTYmQ0c0N2d2tkd0RkZ3hpRG9DUnpZbkxIK1EzZUIKK1BsR05Mc25Zdkw1MTg4QzdQUmdFcVJxUmc1UFZheElhdkEwOTB4c2hqZ2R4ZllWMldrblVFWHdoYUFNaFY1WgpUMXFyeHd1TlNBWCtKSU5hS0JjZFRzYnFGcXhhREhSemwzT0hLMFpndlJ6VGZYSmp0aHJQcjFkNldueEpoK24zCkRlalUzMmplNE44aU10eHJlZE5sMnlMQUE0T2RZMlNOWUl4NnZ4dm80TXBxbkdlOUZCaGtUQTJkQlYxb2YvdnQKQ3FQRmsycXhHeHpidUZZcDM1VTlVSHh4eC9PZEI1b0NEU1ZMZUxHT0VWV2xaU0xGUGY3OTQvRnZWclBOQWlkNApydDIzSXhJY0duRmNRT0Y2S0d5ZTEvMDRlQ2FKZ1FPdm41TEtjYVc0OFFLQmdRRFg4bE1zcHNOdllYTGRTaklyCnJIbFVTTjZOSFFBQy9VYVFuVFlrWnJscjE0ME1oNmhvQ256MzVSZTZrS0tFd1FQWTBINlIvSUpDbVdMNUovZGYKM2pKeW9OWFlxdmpZb1FydHBBSS9paGs5V2ZGdlVIMnRSb0NnaitOUCt3M25TM0lVNHdad2RFeHhKUHV6MzR5MgpyWEl3M2R4ekNzL2Q5WVc5SFFxK0tYSUZqd0tCZ1FET0d2OUNZbFdQa1FCZzd2RjJRSm55T0dVOTZhbCtialFLCnRrN213R0QzVGhzTkJxMjUyQ3drRkIwVVRlUlhrVUh0VDVGaGhUZ1lzRmFWOTQ2WUZmUkdYbkRJTFZuN1BWWFMKUVBkQVhlZTduUXJjREYxb1ZFbGVHV1M1djRJRXdzamhoT1kyVnF1cHJaWWV6Vi9oVzRFcjdxUWVPSWRNcklWawo3WjNTb3FuaHB3S0JnUUM3c0RtTWFKRWFnSWMyUUtPa2crNmNUQTFxZHRjb3dmd1AreVF3dFR2WnVHbzJocjNmClY2WlFTMFM1ZWJaWFRlOUxCY1BNbkx5V3AveDI4NzYxQzBtcmlaRDBGWDNkd3ZMZG94djFIOUZhR28rV29VM3EKU1luSWcrY2MvK2FRcm1sRU1DSExvYmxDNmRMKy9vQ3QwY2liSW1uVmI0TkZ0bno3NW44TTByYndqd0tCZ0ZQTQpXamlOYnFnK2xsN1RCODNDbWxVSFpQSjFUSHFoSi91ckFBMkY3bWJlbE5VSkFCMXRyUlRHTU1TT251YVRvckJ3CkIzWVZDaWZQbW9UQzhIRVpqQVlJWSthZnVkUVNyaEFjWmVyL3d6WmV0WW1lWldRRDBRaTNYbUsvWUllN0FwM2UKd1JNYXpoVGhCUVpsRGpTOFZacWRIcEZDL28vSUhUeForQzhwLzlSRkFvR0FGQkVUcFJDZ0QvZDFBOGVsWDVzagp1TGNBeDlHOUZaQTY3TG1GckQ5b0o0aXYrM0hTblAwaVh6WnNjSnI5SWpSK3Y5Wmswcm93RlNGSVY2U0g3VVF1CjljemNrdkxIemtPNjMzbzViQXhxaE5zdVBFQmc1N25iS2l5SEExSHVhUThTNVlXTjJsR2FQd20rMklacHoyMWEKS1Ftck1VV3dTNjRsSUtGZ21RTjBXYlU9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K"
  publicKey: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFyZHZFM01FQUQ0REhXNFlmQkdJOAo5cklrVVpzWGEzMitqU00vYUUzek94OTVlbmFZNDdTVTVYK2NMdnUySmwxa25TelN4TVZweDMrVGxNdHZidVBVCjFnZ0Yrb2NGSVJXNi8vY2NuSytXak1MQ2FHL0FZTGwzWkpabmpIOXRUWXhscXNKcmplM2Y3UGY2UkRwQ2M0dFEKcm0xMllPS25DR0ZYZGRmMDZkeG03MzBPQndnSDBQRmtrK01vSWo4UmRaUXJEdEpMNGswczFsSlB2RXdLOGphRQp1MjhSb20vSFZIZWFLclJUckxXanN4Ym5BTDNKOWY1MGMyNFRqcWVYT1JEL3ozajhsY2RmaGtKVlg1cWorcW5MCjhMRFBKZWdrNnRWcjR0N2M1Z2dyZVNLaVZMR3YwWE9NZWNIVmUwRG1PSnAybnNEVkhzU2ZQZHhBZXVxU2FhdFAKU1FJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="
---
affinity: {}
fullnameOverride: ''
image:
  pullPolicy: Always
  repository: quay.io/ortelius/ms-nginx
  tag: svc_cat-v10.0.6-g78c39e
  sha: sha256:d5dfc92ba4b4d34f1af7ac16f3d8370f755cfa91f93a786cec547389930fb86f
ingress:
  annotations: {}
  enabled: false
  hosts:
    - chart-example.local
  paths: []
  tls: []
nameOverride: ''
nodeSelector: {}
replicaCount: 1
resources: {}
service:
  port: 80
  type: ClusterIP
tolerations: []
---
replicaCount: 1
image:
  repository: quay.io/ortelius/ms-scorecard
  tag: main-v10.0.43-g624056
  sha: sha256:56d4ea535669f69997fa82bfdaf62870e72a01f5deb75e1dfc3bf224cac0bf60
  pullPolicy: Always
---
DockerRepo: quay.io/ortelius/ms-textfile-crud
DockerSha: 2e1fad49558a
DockerTag: deploy-v10.0.0.62-g104a226
image:
  repository: quay.io/ortelius/ms-textfile-crud
  tag: main-v10.0.9-gec05e7
  sha: sha256:4f6039be082664bab8034aba96e78250db915af448f9dc9e383f2b35348c02c4
---
replicaCount: 1
image:
  repository: quay.io/ortelius/ms-ui
  tag: svc_cat-v10.0.6-g78c39e
  sha: sha256:e4ecaa82ed56f2922589561932bfdab093dfcce2963f8ecebf7fdc9c0a58efb8
---
BuildNumber: 0
Chart: chart/ms-validate-user
ChartNamespace: ortelius
CustomAction: GLOBAL.HelmChart
DockerRepo: quay.io/ortelius/ms-validate-user
DockerSha: 9d17b931bca9
DockerTag: deploy-v10.0.0.68-g6b08a2a
EXT: sh
GitBranch: deploy
GitCommit: 6b08a2a
GitRepo: ortelius/ortelius-ms-validate-user
GitTag: deploy
GitUrl: https://github.com/ortelius/ortelius-ms-validate-user.git
RE_PHYSICAL_HOSTNAME: localhost
RE_PHYSICAL_SERVER: localhost
aks:
  admin: true
  cluster: cluster2-aks
  resourcegroup: cluster1-rg
application: ortelius;10_0_0
builddate: Fri Jul 22 16:58:33 2022
buildid: 438da77b-4f61-414e-ac63-0d105c07072d
buildurl: https://console.cloud.google.com/cloud-build/builds/438da77b-4f61-414e-ac63-0d105c07072d?project=eighth-physics-169321
chart: chart/ms-validate-user
chartnamespace: ortelius
component: ms-validate-user;deploy;v10_0_0_68_g6b08a2a
dockerrepo: quay.io/ortelius/ms-validate-user
dockersha: 9d17b931bca9
dockertag: deploy-v10.0.0.68-g6b08a2a
dropzone: /tmp/tdm.1766.9
environment: aks-cluster
gitcommit: 6b08a2a
gitrepo: ortelius/ortelius-ms-validate-user
gittag: deploy
giturl: https://github.com/ortelius/ortelius-ms-validate-user.git
kubectl_context: cluster2-aks-admin
server_hostname: localhost
server_name: localhost
image:
  repository: quay.io/ortelius/ms-validate-user
  tag: main-v10.0.4-g12fcb1
  sha: sha256:0e181d27701154d71612d3d976f71a68f2d85b2ff5f3211f0fd3ee3d74b6f550
