apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app:  ""
        tier: backend
        track: stable
    spec:
      containers:
        - name: ""
          imagePullPolicy: Always
          volumeMounts:
            - name: jwt-volume
              mountPath: /app/keys
      volumes:
        - name: jwt-volume
          secret:
            secretName: jwtkeys
