apiVersion: v2
name: argocd
description: A Helm chart for argocd
type: application
version: 0.0.1
appVersion: 0.0.1
icon: https://cncf-branding.netlify.app/img/projects/argo/stacked/color/argo-stacked-color.png
maintainers:
  - name: Sacha Wharton