ingress:
  host: localhost

#server:
#  sa:
#    annotations:
#      eks.amazonaws.com/role-arn: arn:aws:iam::<number>:role/oidc-role-argocd-server

#applicationController:
#  resources:
#    requests:
#      cpu: 0.5
#      memory: 1Gi
#    limits:
#      cpu: 1
#      memory: 1Gi

#githubSSO:
#  clientID: "43c45fkj34345"

#proxy:
#  host: proxyv2
#  noProxyHosts: "10.251.0.0/16,44.135.74.0/24,44.135.81.128/25,10.100.0.0/16,172.20.0.0/16,.svc,.local,.cluster.local,.svc.cluster.local,localhost,127.0.0.1,.internal,169.254.169.254,argocd-dex-server,argocd-metrics,argocd-redis,argocd-repo-server,argocd-server,argocd-server-metrics"

servers:
  localhost: https://kubernetes.default.svc

repos:
  - helm-argocd
  - helm-bookinfo
  - playground-generic-microservice-inheritor
  - helm-guestbook-demo
  - playground-generic-logstash-inheritor
  - argocdapps-playground

#helmrepoBackendS3Location: ortelius-in-a-box-helmrepobackend/charts
